In [1]:
import numpy as np
import statsmodels.api as sm
from statsmodels.regression.linear_model import OLS


y = [1969.0821256 ,  257.63888889,  188.99082569,  624.06639004,
        130.22556391,  336.65791776,  603.48837209,  180.28169014,
        498.91472868,  478.07228916,  362.35504014,  654.48818898,
        461.9047619 ,  317.88856305,   60.7518797 ,  305.15672396,
        315.18771331,  301.98675497,  184.48275862,   75.14124294,
        322.59164535,  250.30927835,  362.07892204,  847.93577982,
        898.79518072,  417.98990363,  303.13901345,  410.86300543,
        374.27779976,  243.46723044,  310.33210332,  392.58037923,
        423.92523364,  240.63400576,  208.5624509 ,  491.56311315,
        267.0122177 ,  271.21083827,  204.86267447,  297.36291335,
        251.85487159,  333.56670556,  208.40840841,  407.71734077,
        366.62286465,  502.98898794,  249.10820452,  529.97601918]

# Independent variable 1
x1 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
0, 1]

# Independent variable 2
x2 = [56, 96, 90, 86, 92, 64, 54, 84, 72, 62, 60, 52, 58, 80, 98, 76, 70,
       74, 82, 94, 66, 78, 68, 24, 20,  8, 32, 30,  6, 40, 18,  4, 10, 46,
       44, 22, 26, 34, 48, 28, 38, 16, 36, 14, 42,  2, 50, 12]
# Independent variable 3

x3 = [0.18, 0.24, 0.34, 0.46, 0.62, 0.64, 0.66, 0.68, 0.76, 0.84, 0.86,
       1.  , 1.02, 1.04, 1.1 , 1.48, 1.56, 1.58, 1.6 , 1.66, 1.68, 1.86,
       1.9 , 2.1 , 2.1 , 2.18, 2.22, 2.26, 2.4 , 2.42, 2.48, 2.54, 2.66,
       2.7 , 2.76, 2.86, 2.9 , 2.9 , 2.96, 3.2 , 3.24, 3.4 , 3.52, 3.58,
       3.58, 3.58, 3.88, 4.  ]



In [2]:
x = np.column_stack((x1,x2,x3))
print(x)

[[ 0.   56.    0.18]
 [ 0.   96.    0.24]
 [ 0.   90.    0.34]
 [ 0.   86.    0.46]
 [ 0.   92.    0.62]
 [ 0.   64.    0.64]
 [ 0.   54.    0.66]
 [ 0.   84.    0.68]
 [ 0.   72.    0.76]
 [ 0.   62.    0.84]
 [ 0.   60.    0.86]
 [ 0.   52.    1.  ]
 [ 0.   58.    1.02]
 [ 0.   80.    1.04]
 [ 0.   98.    1.1 ]
 [ 0.   76.    1.48]
 [ 0.   70.    1.56]
 [ 0.   74.    1.58]
 [ 0.   82.    1.6 ]
 [ 0.   94.    1.66]
 [ 0.   66.    1.68]
 [ 0.   78.    1.86]
 [ 0.   68.    1.9 ]
 [ 1.   24.    2.1 ]
 [ 1.   20.    2.1 ]
 [ 1.    8.    2.18]
 [ 1.   32.    2.22]
 [ 1.   30.    2.26]
 [ 1.    6.    2.4 ]
 [ 1.   40.    2.42]
 [ 1.   18.    2.48]
 [ 1.    4.    2.54]
 [ 1.   10.    2.66]
 [ 1.   46.    2.7 ]
 [ 1.   44.    2.76]
 [ 1.   22.    2.86]
 [ 1.   26.    2.9 ]
 [ 1.   34.    2.9 ]
 [ 1.   48.    2.96]
 [ 1.   28.    3.2 ]
 [ 1.   38.    3.24]
 [ 1.   16.    3.4 ]
 [ 1.   36.    3.52]
 [ 1.   14.    3.58]
 [ 1.   42.    3.58]
 [ 1.    2.    3.58]
 [ 0.   50.    3.88]
 [ 1.   12.  

In [3]:
x = sm.add_constant(x, prepend=True)
print(x)

[[ 1.    0.   56.    0.18]
 [ 1.    0.   96.    0.24]
 [ 1.    0.   90.    0.34]
 [ 1.    0.   86.    0.46]
 [ 1.    0.   92.    0.62]
 [ 1.    0.   64.    0.64]
 [ 1.    0.   54.    0.66]
 [ 1.    0.   84.    0.68]
 [ 1.    0.   72.    0.76]
 [ 1.    0.   62.    0.84]
 [ 1.    0.   60.    0.86]
 [ 1.    0.   52.    1.  ]
 [ 1.    0.   58.    1.02]
 [ 1.    0.   80.    1.04]
 [ 1.    0.   98.    1.1 ]
 [ 1.    0.   76.    1.48]
 [ 1.    0.   70.    1.56]
 [ 1.    0.   74.    1.58]
 [ 1.    0.   82.    1.6 ]
 [ 1.    0.   94.    1.66]
 [ 1.    0.   66.    1.68]
 [ 1.    0.   78.    1.86]
 [ 1.    0.   68.    1.9 ]
 [ 1.    1.   24.    2.1 ]
 [ 1.    1.   20.    2.1 ]
 [ 1.    1.    8.    2.18]
 [ 1.    1.   32.    2.22]
 [ 1.    1.   30.    2.26]
 [ 1.    1.    6.    2.4 ]
 [ 1.    1.   40.    2.42]
 [ 1.    1.   18.    2.48]
 [ 1.    1.    4.    2.54]
 [ 1.    1.   10.    2.66]
 [ 1.    1.   46.    2.7 ]
 [ 1.    1.   44.    2.76]
 [ 1.    1.   22.    2.86]
 [ 1.    1.   26.    2.9 ]
 

In [4]:
r = OLS(y,x).fit().params
print(r)

[1361.56486903 -233.34199655  -10.51263665 -168.72071646]


In [5]:
OLS(y,x).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.363
Model:                            OLS   Adj. R-squared:                  0.319
Method:                 Least Squares   F-statistic:                     8.342
Date:                Tue, 25 Feb 2020   Prob (F-statistic):           0.000168
Time:                        14:56:58   Log-Likelihood:                -328.72
No. Observations:                  48   AIC:                             665.4
Df Residuals:                      44   BIC:                             672.9
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1361.5649    204.766      6.649      0.000     948.886    1774.243
x1          -233.3420    153.989     -1.515      0.137    -543.687      77.003
x2           -10.5126      2.459     -4.275      0.000     -15.469      -5.556
x3          -168.7207     52.589     -3.208      0.002    -274.706     -62.735
==============================================================================
Omnibus:                       62.282   Durbin-Watson:                   1.256
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              530.769
Skew:                           3.245   Prob(JB):                    5.56e-116
Kurtosis:                      17.942   Cond. No.                         377.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [9]:
m = np.shape(x2)[0]
print(m)
print(np.ones(m))
X = np.column_stack((np.ones(m),x1,x2,x3))
print(X)

48
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[ 1.    0.   56.    0.18]
 [ 1.    0.   96.    0.24]
 [ 1.    0.   90.    0.34]
 [ 1.    0.   86.    0.46]
 [ 1.    0.   92.    0.62]
 [ 1.    0.   64.    0.64]
 [ 1.    0.   54.    0.66]
 [ 1.    0.   84.    0.68]
 [ 1.    0.   72.    0.76]
 [ 1.    0.   62.    0.84]
 [ 1.    0.   60.    0.86]
 [ 1.    0.   52.    1.  ]
 [ 1.    0.   58.    1.02]
 [ 1.    0.   80.    1.04]
 [ 1.    0.   98.    1.1 ]
 [ 1.    0.   76.    1.48]
 [ 1.    0.   70.    1.56]
 [ 1.    0.   74.    1.58]
 [ 1.    0.   82.    1.6 ]
 [ 1.    0.   94.    1.66]
 [ 1.    0.   66.    1.68]
 [ 1.    0.   78.    1.86]
 [ 1.    0.   68.    1.9 ]
 [ 1.    1.   24.    2.1 ]
 [ 1.    1.   20.    2.1 ]
 [ 1.    1.    8.    2.18]
 [ 1.    1.   32.    2.22]
 [ 1.    1.   30.    2.26]
 [ 1.    1.    6.    2.4 ]
 [ 1.    1.   40.    2.42]
 [ 1.    1.   18.    2.48]
 [ 1.    1.  

In [10]:
coeff = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
print(coeff)

[1361.56486903 -233.34199655  -10.51263665 -168.72071646]


In [ ]:
# 1361.56486903 -233.34199655  -10.51263665 -168.72071646
# 1361.56486903 -233.34199655  -10.51263665 -168.72071646